CREATE TABLE `seller_settings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text DEFAULT '' NOT NULL,
	`sub_headline` text,
	`street` text DEFAULT '' NOT NULL,
	`street_number` text DEFAULT '' NOT NULL,
	`postal_code` text DEFAULT '' NOT NULL,
	`city` text DEFAULT '' NOT NULL,
	`country` text DEFAULT 'DE' NOT NULL,
	`phone_number` text,
	`email` text,
	`contact_name` text,
	`contact_phone` text,
	`contact_email` text,
	`tax_number` text,
	`vat_id` text,
	`court` text,
	`register_number` text,
	`managing_director` text,
	`bank_name` text,
	`iban` text,
	`bic` text,
	`logo_url` text,
	`updated_at` text NOT NULL
);
